name: Secure Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Static Analysis with Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'

      - name: Build Docker image
        run: docker build -t my-microservice:${{ github.sha }} .

      - name: Scan docker image using Trivy
        uses: aquasecurity/trivy-action@v0.10.5
        with:
          image-ref: my-microservice:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image on success
        run: docker push my-microservice:${{ github.sha }}

