name: Deploy Docker App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repo
      - name: Checkout code
        uses: actions/checkout@v3

      # (Optional) List repo files for debugging
      - name: List files before upload
        run: ls -la

      # Securely copy files to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/my-microservice"

      # SSH into EC2 and rebuild/restart Docker app
      - name: Deploy and restart Docker app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/my-microservice
            ls -la                # confirm Dockerfile exists
            docker build -t my-microservice .
            docker stop my-microservice || true
            docker rm my-microservice || true
            docker run -d --env-file .env -p 80:3000 --name my-microservice my-microservice
